[device]
# Ngẫu nhiên hóa MAC khi đang quét tìm Wifi (tăng tính riêng tư khi di chuyển)
wifi.scan-rand-mac-address=yes

[connection]
# Sử dụng MAC giả cố định cho từng mạng Wifi (tránh phải login lại trường học)
wifi.cloned-mac-address=stable
ethernet.cloned-mac-address=random
