#!/bin/sh

# keyhint rofi tool to search used keybindings in i3wm

I3_DIR=$HOME/.config/i3
I3_CONFIG=$I3_DIR/config
mod_key=$(sed -nre 's/^set \$mod (.*)/\1/p' ${I3_CONFIG})
# bindings live in the included conf.d/*.conf files (see ~/.config/i3/config)
cat ${I3_CONFIG} ${I3_DIR}/conf.d/*.conf ${I3_DIR}/local.conf 2>/dev/null | grep "^bindsym" \
    | sed "s/-\(-\w\+\)\+//g;s/\$mod/${mod_key}/g;s/Mod1/Alt/g;s/exec //;s/bindsym //;s/^\s\+//;s/^\([^ ]\+\) \(.\+\)$/\2: \1/;s/^\s\+//" \
    | tr -s ' ' \
    | rofi -dmenu -theme ~/.config/rofi/rofikeyhint.rasi
