
#!/bin/bash
# migrate_user_to_system_advanced.sh
# Migrate lua/user structure to lua/system System Architecture (auto-generate system/init.lua)

# -----------------------------
# Cấu hình thư mục
# -----------------------------
USER_DIR="${1:-$HOME/.config/nvim/lua/user}"      # Thư mục cũ
SYSTEM_DIR="${2:-$HOME/.config/nvim/lua/system}"  # Thư mục đích

echo "🚀 Migrating Neovim config from $USER_DIR → $SYSTEM_DIR ..."

# Tạo thư mục system cơ bản
mkdir -p "$SYSTEM_DIR"/{constitution,kernel,runtime,plugins,plugins/cmp,plugins/lsp/servers,plugins/snippets_data,plugins/tools,plugins/ui,utils}

# -----------------------------
# 1️⃣ Constitution
# -----------------------------
echo "📦 Migrating constitution files..."
cp -v "$USER_DIR/config"/{cmp_sources.lua,lsp_capabilities.lua,lsp_ui.lua} "$SYSTEM_DIR/constitution/" 2>/dev/null || true

# -----------------------------
# 2️⃣ Runtime
# -----------------------------
echo "📦 Migrating runtime files..."
cp -v "$USER_DIR/config/lsp_on_attach.lua" "$SYSTEM_DIR/runtime/lsp_attach.lua" 2>/dev/null || true

# -----------------------------
# 3️⃣ Kernel
# -----------------------------
echo "📦 Migrating kernel files..."
cp -v "$USER_DIR/core/options.lua" "$SYSTEM_DIR/kernel/options.lua" 2>/dev/null || true
cp -v "$USER_DIR/core/keymaps.lua" "$SYSTEM_DIR/kernel/keynames.lua" 2>/dev/null || true
cp -v "$USER_DIR/core/autocommands.lua" "$SYSTEM_DIR/kernel/autocommands.lua" 2>/dev/null || true
cp -v "$USER_DIR/core/init.lua" "$SYSTEM_DIR/kernel/init.lua" 2>/dev/null || true

# -----------------------------
# 4️⃣ Plugins
# -----------------------------
echo "📦 Migrating plugins..."
# Plugin root files
cp -v "$USER_DIR/plugins"/{colorscheme.lua,format.lua,git.lua,snippets.lua,terminal.lua,treesitter.lua,ts_comment.lua} "$SYSTEM_DIR/plugins/" 2>/dev/null || true

# Plugin folders
rsync -av --ignore-existing "$USER_DIR/plugins/cmp/" "$SYSTEM_DIR/plugins/cmp/" 2>/dev/null
rsync -av --ignore-existing "$USER_DIR/plugins/lsp/servers/" "$SYSTEM_DIR/plugins/lsp/servers/" 2>/dev/null
rsync -av --ignore-existing "$USER_DIR/plugins/snippets_data/" "$SYSTEM_DIR/plugins/snippets_data/" 2>/dev/null
rsync -av --ignore-existing "$USER_DIR/plugins/tools/" "$SYSTEM_DIR/plugins/tools/" 2>/dev/null
rsync -av --ignore-existing "$USER_DIR/plugins/ui/" "$SYSTEM_DIR/plugins/ui/" 2>/dev/null

# -----------------------------
# 5️⃣ Utils
# -----------------------------
echo "📦 Migrating utils..."
cp -v "$USER_DIR/utils/init.lua" "$SYSTEM_DIR/utils/init.lua" 2>/dev/null || true

# -----------------------------
# 6️⃣ Generate system/init.lua
# -----------------------------
echo "📦 Generating system/init.lua ..."
cat <<EOF > "$SYSTEM_DIR/init.lua"
-- system/init.lua
-- Auto-generated by migrate_user_to_system_advanced.sh
-- Load order: constitution -> kernel -> runtime -> plugins

-- Constitution
local cons = {
    "cmp_sources",
    "lsp_capabilities",
    "lsp_ui",
}

for _, mod in ipairs(cons) do
    local ok, m = pcall(require, "system.constitution." .. mod)
    if ok and type(m.setup) == "function" then
        m.setup()
    end
end

-- Kernel
require("system.kernel")

-- Runtime
require("system.runtime.lsp_attach")

-- Plugins (lazy.nvim)
require("lazy").setup("system.plugins")

print("✅ System architecture loaded!")
EOF

# -----------------------------
# 7️⃣ Root init.lua
# -----------------------------
echo "📦 Creating root init.lua..."
cat <<'EOF' > "$(dirname "$SYSTEM_DIR")/init.lua"
vim.g.mapleader = " "
vim.g.maplocalleader = " "
require("system")
EOF

# -----------------------------
# 8️⃣ Kết thúc
# -----------------------------
echo "✅ Migration complete! Structure under $(dirname "$SYSTEM_DIR"):"
tree -L 3 "$(dirname "$SYSTEM_DIR")"
