return {
	{ import = "system.plugins.ui.bufferline"         },
	{ import = "system.plugins.ui.lualine"            },
	{ import = "system.plugins.ui.neo-tree"           },
	{ import = "system.plugins.ui.aerial-symbols-outline" },
	{ import = "system.plugins.ui.trouble"            },
	{ import = "system.plugins.ui.indent-blankline"   },
	{ import = "system.plugins.ui.whichkey"           },
	{ import = "system.plugins.ui.beacon-cursor-flash" },
	{ import = "system.plugins.ui.smear-cursor-trail" },
	-- recommended additions
	{ import = "system.plugins.ui.treesitter-context" },
	{ import = "system.plugins.ui.illuminate-highlight-word" },
	{ import = "system.plugins.ui.notify"             },
	{ import = "system.plugins.ui.snacks"             },
	{ import = "system.plugins.ui.colorizer"          },
	-- posh IDE polish
	{ import = "system.plugins.ui.noice"              },
	{ import = "system.plugins.ui.dropbar"            },
	{ import = "system.plugins.ui.tiny-inline-diagnostic" },
	{ import = "system.plugins.ui.satellite"          },
	{ import = "system.plugins.ui.fidget-lsp-progress" },
	{ import = "system.plugins.ui.mini-map"            },
	{ import = "system.plugins.ui.nvim-biscuits"       },
}
