# Font Configuration
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.5

# Advanced Font Styling
disable_ligatures never

# Window Layout & Geometry
window_padding_width 4

# Window Decorations (Works beautifully in Xfce/i3)
hide_window_decorations no
