# ========================
# Main Kitty Configuration
# ========================

include theme.conf
include keybindings.conf

# ------------------------
# Window
# ------------------------
window_title Kitty-Terminal
window_padding_width 4

# ------------------------
# Font
# ------------------------
font_family      JetBrainsMono NF Light
bold_font        JetBrainsMono NF Bold
italic_font      JetBrainsMono NF Light Italic
bold_italic_font JetBrainsMono NF Bold Italic
font_size        10.0
disable_ligatures always

# ------------------------
# Performance
# ------------------------
scrollback_lines 20000
repaint_delay 8
input_delay 2
sync_to_monitor yes

# ------------------------
# Bell
# ------------------------
enable_audio_bell no
visual_bell no

# ------------------------
# Shell
# ------------------------
allow_remote_control yes
shell_integration enabled
