return {
	{ import = "system.plugins.tools.fzf" },
	{ import = "system.plugins.tools.quicker-quickfix-ui" },
	{ import = "system.plugins.tools.vim-tmux-navigator" },
	{ import = "system.plugins.tools.persistence" },
	{ import = "system.plugins.tools.nvim-dap" },
	{ import = "system.plugins.tools.crates-cargo-versions" },
	{ import = "system.plugins.tools.flash-jump-motion" },
	{ import = "system.plugins.tools.todo" },
	{ import = "system.plugins.tools.numb-line-preview" },
	{ import = "system.plugins.tools.treesj-split-join" },
	{ import = "system.plugins.tools.surround" },
	{ import = "system.plugins.tools.autopairs" },
	{ import = "system.plugins.tools.terminal" },
	{ import = "system.plugins.tools.diffview" },
	{ import = "system.plugins.tools.grug-far-search-replace" },
	{ import = "system.plugins.tools.ufo-code-folding" },
	-- recommended additions
	{ import = "system.plugins.tools.harpoon-file-bookmarks" },
	{ import = "system.plugins.tools.undotree" },
	{ import = "system.plugins.tools.neogen-docstring-gen" },
	{ import = "system.plugins.tools.dial-increment-decrement" },
	{ import = "system.plugins.tools.mini-ai-textobjects" },
	{ import = "system.plugins.tools.mini-bracketed-motions" },
	{ import = "system.plugins.tools.cmake-tools" },
	{ import = "system.plugins.tools.clangd-extensions" },
	{ import = "system.plugins.tools.kulala-rest-client" },
	{ import = "system.plugins.tools.inc-rename-lsp-preview" },
	{ import = "system.plugins.tools.neotest" },
	{ import = "system.plugins.tools.overseer-task-runner" },
	{ import = "system.plugins.tools.refactoring" },
	{ import = "system.plugins.tools.claudecode" },
}
